spring:
# Neo4J
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: test123
# Redis
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 40000
# Postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=music
    username: test1234
    password: test1234
# JPA & Hibernate
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: true
# MongoDB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: music
# Neo4J
    neo4j:
      database: neo4j
# Others
  sql:
    init:
      mode: always
      continue-on-error: true
  main:
    allow-bean-definition-overriding: true
# Server port
server:
  port: 80
